echoServerByPoll:echoServerByPoll.cpp CLEventManager.cpp CLEventManagerByPoll.cpp CLSocketPack.cpp 
	g++ echoServerByPoll.cpp CLEventManager.cpp CLEventManagerByPoll.cpp CLSocketPack.cpp -o echoServerByPoll -g
